name: CI/CD - Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Change if your deployment branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout code
        uses: actions/checkout@v4

      - name: ğŸ§± Build Docker Image
        run: |
          docker build -t gke-sample-extraction-track-setup:v1 .
          echo "âœ… Docker build complete"
      - name: date and time checking
        run: | 
          date
          time

      - name: ğŸ” Check available Docker images
        run: docker images
